# Generated by Django 3.2.6 on 2021-11-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_availability_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Positioning',
        ),
    ]
