# Generated by Django 3.2.6 on 2021-11-14 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_positioning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
