# Generated by Django 3.2.6 on 2021-12-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0002_event_game_type'),
        ('benchcoachproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teamsnap_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchcoach_object', to='teamsnap.user'),
        ),
    ]
