# Generated by Django 3.2.6 on 2021-12-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0016_auto_20211212_2240'),
        ('benchcoach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teamsnap_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.user'),
        ),
    ]
