# Generated by Django 3.2.6 on 2021-12-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchcoach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(null=True),
        ),
    ]
