# Generated by Django 3.2.6 on 2021-12-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchcoach', '0003_auto_20211213_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='benchcoach/static/user_files/'),
        ),
    ]
