# Generated by Django 3.2.6 on 2021-12-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0019_auto_20211216_1851'),
        ('benchcoach', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsnapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='benchcoach.profile')),
            ],
        ),
    ]
