# Generated by Django 3.2.6 on 2021-12-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0019_auto_20211216_1851'),
        ('benchcoach', '0007_teamsnapsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teamsnap_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.user'),
        ),
    ]
