# Generated by Django 3.2.6 on 2021-12-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
