# Generated by Django 3.2.6 on 2021-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='formatted_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='teamsnap_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='teamsnap_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='teamsnap_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamsnap_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='teamsnap_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
