# Generated by Django 3.2.6 on 2021-11-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0002_auto_20211121_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='bencoach_event',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='venue',
            new_name='bencoach_venue',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='player',
            new_name='bencoach_player',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='bencoach_team',
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_non_player',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='jersey_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team'),
        ),
    ]
