# Generated by Django 3.2.6 on 2021-12-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benchcoach', '0002_alter_player_jersey_number'),
        ('teamsnap', '0002_event_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='managed_by_team',
        ),
        migrations.RemoveField(
            model_name='event',
            name='managed_by_team',
        ),
        migrations.RemoveField(
            model_name='location',
            name='managed_by_team',
        ),
        migrations.RemoveField(
            model_name='member',
            name='managed_by_team',
        ),
        migrations.RemoveField(
            model_name='opponent',
            name='managed_by_team',
        ),
        migrations.AddField(
            model_name='availability',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team', verbose_name='managed by team'),
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team', verbose_name='managed by team'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='benchcoach_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_lineupentry', to='benchcoach.positioning'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team', verbose_name='managed by team'),
        ),
        migrations.AddField(
            model_name='location',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team', verbose_name='managed by team'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team', verbose_name='managed by team'),
        ),
        migrations.AddField(
            model_name='opponent',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team', verbose_name='managed by team'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='benchcoach_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_availability', to='benchcoach.availability'),
        ),
        migrations.AlterField(
            model_name='event',
            name='benchcoach_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_event', to='benchcoach.event'),
        ),
        migrations.AlterField(
            model_name='location',
            name='benchcoach_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_location', to='benchcoach.venue'),
        ),
        migrations.AlterField(
            model_name='member',
            name='benchcoach_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_member', to='benchcoach.player'),
        ),
        migrations.AlterField(
            model_name='opponent',
            name='benchcoach_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_opponent', to='benchcoach.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='benchcoach_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_team', to='benchcoach.team'),
        ),
        migrations.AlterUniqueTogether(
            name='lineupentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lineupentry',
            name='managed_by_team',
        ),
    ]
