# Generated by Django 3.2.6 on 2021-12-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0003_auto_20211219_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_game',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_non_player',
            field=models.BooleanField(null=True),
        ),
    ]
