# Generated by Django 3.2.6 on 2021-12-29 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benchcoach', '0002_alter_player_jersey_number'),
        ('teamsnap', '0004_auto_20211222_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='benchcoach_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_object+', to='benchcoach.availability'),
        ),
        migrations.AlterField(
            model_name='event',
            name='benchcoach_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_object+', to='benchcoach.event'),
        ),
        migrations.AlterField(
            model_name='lineupentry',
            name='benchcoach_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_object+', to='benchcoach.positioning'),
        ),
        migrations.AlterField(
            model_name='location',
            name='benchcoach_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_object+', to='benchcoach.venue'),
        ),
        migrations.AlterField(
            model_name='member',
            name='benchcoach_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_object+', to='benchcoach.player'),
        ),
        migrations.AlterField(
            model_name='opponent',
            name='benchcoach_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_object+', to='benchcoach.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='benchcoach_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_object+', to='benchcoach.team'),
        ),
    ]
