# Generated by Django 3.2.6 on 2021-12-29 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benchcoach', '0002_alter_player_jersey_number'),
        ('teamsnap', '0006_auto_20211228_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='benchcoach_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_availability', to='benchcoach.availability'),
        ),
        migrations.AlterField(
            model_name='event',
            name='benchcoach_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_event', to='benchcoach.event'),
        ),
        migrations.AlterField(
            model_name='lineupentry',
            name='benchcoach_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_lineupentry', to='benchcoach.positioning'),
        ),
        migrations.AlterField(
            model_name='location',
            name='benchcoach_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_location', to='benchcoach.venue'),
        ),
        migrations.AlterField(
            model_name='member',
            name='benchcoach_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_member', to='benchcoach.player'),
        ),
        migrations.AlterField(
            model_name='opponent',
            name='benchcoach_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_opponent', to='benchcoach.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='benchcoach_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_team', to='benchcoach.team'),
        ),
    ]
