# Generated by Django 3.2.6 on 2021-11-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0007_auto_20211121_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'availabilities'},
        ),
    ]
