# Generated by Django 3.2.6 on 2021-12-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0008_alter_availability_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status_code',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No'), (2, 'Maybe'), (None, 'Unknown')], default=None, null=True),
        ),
    ]
