# Generated by Django 3.2.6 on 2021-11-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0008_alter_availability_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='points_for_opponent',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='points_for_team',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
