# Generated by Django 3.2.6 on 2021-11-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0009_auto_20211121_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_game',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
