# Generated by Django 3.2.6 on 2022-05-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0005_auto_20211224_1042'),
        ('teamsnap', '0009_alter_availability_status_code'),
    ]

    operations = [
    ]
