# Generated by Django 3.2.6 on 2021-11-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0011_lineupentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupentry',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='teamsnap_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
