# Generated by Django 3.2.6 on 2021-11-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0012_auto_20211121_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineupentry',
            name='name',
        ),
    ]
