# Generated by Django 3.2.6 on 2021-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0014_alter_lineupentry_teamsnap_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='bencoach_event',
            new_name='benchcoach_event',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='bencoach_venue',
            new_name='benchcoach_venue',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='bencoach_player',
            new_name='benchcoach_player',
        ),
        migrations.AlterField(
            model_name='lineupentry',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
