# Generated by Django 3.2.6 on 2021-12-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0015_auto_20211210_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='benchcoach_availability',
            new_name='benchcoach_object',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='benchcoach_event',
            new_name='benchcoach_object',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='benchcoach_venue',
            new_name='benchcoach_object',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='benchcoach_player',
            new_name='benchcoach_object',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
