# Generated by Django 3.2.6 on 2021-12-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0017_auto_20211212_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_teams',
            field=models.ManyToManyField(to='teamsnap.Team'),
        ),
    ]
