# Generated by Django 3.2.6 on 2021-12-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_availability'),
        ('teamsnap', '0018_user_managed_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='team',
            new_name='managed_by_team',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='team',
            new_name='managed_by_team',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='team',
            new_name='managed_by_team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='bencoach_team',
            new_name='benchcoach_object',
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='managed_by_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team'),
        ),
        migrations.AddField(
            model_name='location',
            name='managed_by_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='managed_by_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='benchcoach_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsnap_event', to='events.event'),
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamsnap_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('managed_by_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsnap.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='teamsnap.opponent'),
        ),
    ]
