# Generated by Django 3.2.6 on 2021-12-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0019_auto_20211216_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='teamsnap_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='teamsnap_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='teamsnap_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='teamsnap_id',
        ),
        migrations.RemoveField(
            model_name='opponent',
            name='teamsnap_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamsnap_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teamsnap_id',
        ),
    ]
