# Generated by Django 3.2.6 on 2021-12-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0022_auto_20211216_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineupentry',
            name='teamsnap_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='managed_by_team',
        ),
    ]
