# Generated by Django 3.2.6 on 2021-12-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsnap', '0023_auto_20211216_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='created_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='updated_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opponent',
            name='created_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opponent',
            name='updated_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default='2000-10-31T01:30:00.000-05:00'),
            preserve_default=False,
        ),
    ]
