# Generated by Django 3.2.6 on 2021-12-16 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('teamsnap', '0024_auto_20211216_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='opponent',
            name='benchcoach_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
