# Generated by Django 3.2.6 on 2021-11-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0002_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.IntegerField(choices=[(2, 'Yes'), (0, 'No'), (1, 'MAY'), (-1, 0)], default=-1),
        ),
    ]
