# Generated by Django 3.2.6 on 2021-12-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0007_alter_positioning_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioning',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
