# Generated by Django 3.2.6 on 2021-11-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='StatLine',
        ),
    ]
